Fix typo in OrderLineDiscount model name
If a project has overridden the OrderDiscount model, this causes the following
exception:

```
  File "/usr/local/lib/python3.11/site-packages/oscar/core/loading.py", line 260, in get_model
    import_module("%s.%s" % (app_config.name, MODELS_MODULE_NAME))
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<FOO>/order/models.py", line 1081, in <module>
    from oscar.apps.order.models import *  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'oscar.apps.order.models' has no attribute 'OrderDiscount'. Did you mean: 'OrderLineDiscount'?
```