Refs #1814 Fix migrations in Python3
The makemigrations command is broken in Python3 because the migration added in
f21c6c6a98 use byte-string regexes. This results in an exception being thrown:
`AttributeError: 'bytes' object has no attribute 'pattern'`. Switching to
raw strings fixes the issue.